name: rn-learn CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Generate database migrations
        run: yarn drizzle
      - name: Typescript compiler
        run: yarn tsc
      - name: Lint
        run: yarn lint
      - name: Run unit tests
        run: yarn test --silent
